<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LaudoForm\F_AnaliseHipoventilacao.cs" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="WMPLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>6bf52a50-394a-11d3-b153-00c04f79faa6</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="AxWMPLib">
      <WrapperTool>aximp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>6bf52a50-394a-11d3-b153-00c04f79faa6</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
    <COMReference Include="Microsoft.Office.Interop.Word">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>7</VersionMinor>
      <VersionMajor>8</VersionMajor>
      <Guid>00020905-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="Microsoft.Office.Interop.Excel">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>9</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>00020813-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="ACTIVEXLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>012f24c1-35b0-11d0-bf2d-0000e8d0d146</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="ADODB">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>8</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>2a75196c-d9eb-4129-b803-931327f72d5c</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Accord" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Audio" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Math" Version="3.8.2-alpha" />
    <PackageReference Include="Accord.Statistics" Version="3.8.2-alpha" />
    <PackageReference Include="Cyotek.Windows.Forms.ColorPicker" Version="2.0.0-beta.7" />
    <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
    <PackageReference Include="MathNet.Filtering" Version="0.7.0" />
    <PackageReference Include="MathNet.Numerics" Version="6.0.0-beta1" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageReference Include="MetroFramework" Version="1.2.0.3" />
    <PackageReference Include="MetroFramework.Design" Version="1.2.0.3" />
    <PackageReference Include="MetroFramework.Fonts" Version="1.2.0.3" />
    <PackageReference Include="MetroFramework.RunTime" Version="1.2.0.3" />
    <PackageReference Include="MetroModernUI" Version="1.4.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.5" />
    <PackageReference Include="NVAPI" Version="1.0.440" />
    <PackageReference Include="ObjectTK" Version="2.0.0-pre.9" />
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="Pandas.NET" Version="0.6.0" />
    <PackageReference Include="PDFsharp" Version="6.2.0-preview-1" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpGL.SceneGraph" Version="3.1.1" />
    <PackageReference Include="SharpGL.WinForms" Version="3.1.1" />
    <PackageReference Include="SharpGL.WPF" Version="3.1.1" />
    <PackageReference Include="SharpGLforWinForms" Version="2.4.0" />
    <PackageReference Include="SharpGLforWPF" Version="2.4.0" />
    <PackageReference Include="System.Data.Odbc" Version="8.0.0" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.0-rc.2.25502.107" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0-preview.1.21102.12" />
    <PackageReference Include="Unity.Container" Version="5.11.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GravaMDB">
      <HintPath>BD\GravaMDB.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="C:\Users\dev_i\.nuget\packages\sharpgl.winforms\3.1.1\contentFiles\any\netcoreapp3.1\SharpGL.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="C:\Users\dev_i\.nuget\packages\sharpgl.winforms\3.1.1\contentFiles\any\netcoreapp3.1\SharpGL.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="BD\GravaMDB.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BD\GravaMDB.pdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ClassesBDNano.DLL">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configuração.mdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Diretorios.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Exames\LaudoPoli Completo - Segmentos Laudo.DOC Laudo.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\depositphotos_2752796-stock-illustration-web-buttons.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\iCelera.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\icelera.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN0Select.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN1Select.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN2Select.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoN3Select.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNN.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNNSelect.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNR.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNRSelect.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNTSelect.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\IcoNumericos\IcoNVazio.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\istockphoto-163268725-1024x1024 %281%29.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\istockphoto-163268725-1024x1024.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icones\pernaEvento.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="IMG\icelera.ico.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\DadosPaciente.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\EEG\Laudo1.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\EEG\Laudo2.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\EEG\LaudoME.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Graficos para laudo.xls">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo Capnógrafo.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo Infantil.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo Multipla Latencia.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo Respiratório com Carga Hipoxica.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo Respiratório.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo1.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\Laudo2.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli BEBE até 2 meses.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli BIPAP.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Completo - Segmentos.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Completo - Split Night.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli CPAP.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Eventos Posicao.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli INFANTIL 2 a 24 Meses.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Manual 2017.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Novo Manual - 1.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Novo Manual - 2.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Novo Manual - HipoVentilacao.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Novo Manual - RERA.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\LaudoPoli Novo Manual 89 - RERA.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Laudos\~%24udoPoli Completo - Split Night.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="lngPortugues.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="nvapi.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\DataSources\LeituraBanco.datasource">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Relatorios.mdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fundo-Recovered - Copia.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fundo-Recovered.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fundo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Retorno\Dessat.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Txt%27s\Canais.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Txt%27s\Diretorios.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Txt%27s\Serie.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>